// <auto-generated />
using System;
using Lesson_5;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lesson_5.Migrations
{
    [DbContext(typeof(InternetStoreContext))]
    [Migration("20240422164017_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("ClientSequence");

            modelBuilder.HasSequence("PersonalSequence");

            modelBuilder.HasSequence("ProductSequence");

            modelBuilder.Entity("Lesson_5.Models.Call", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CallTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("ConsultantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ConsultantId");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("Lesson_5.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [ClientSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<long>("Age")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Lesson_5.Models.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [PersonalSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<long>("Age")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personals");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Lesson_5.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [ProductSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Lesson_5.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultantId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Lesson_5.Models.Supply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("Lesson_5.Models.Customer", b =>
                {
                    b.HasBaseType("Lesson_5.Models.Client");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Lesson_5.Models.Provider", b =>
                {
                    b.HasBaseType("Lesson_5.Models.Client");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("Lesson_5.Models.Consultant", b =>
                {
                    b.HasBaseType("Lesson_5.Models.Personal");

                    b.ToTable("Consultants");
                });

            modelBuilder.Entity("Lesson_5.Models.Manager", b =>
                {
                    b.HasBaseType("Lesson_5.Models.Personal");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Lesson_5.Models.Book", b =>
                {
                    b.HasBaseType("Lesson_5.Models.Product");

                    b.Property<long>("ChapterCount")
                        .HasColumnType("bigint");

                    b.Property<long>("PagesCount")
                        .HasColumnType("bigint");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Lesson_5.Models.Clothe", b =>
                {
                    b.HasBaseType("Lesson_5.Models.Product");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Clothes");
                });

            modelBuilder.Entity("Lesson_5.Models.Technique", b =>
                {
                    b.HasBaseType("Lesson_5.Models.Product");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.ToTable("Techniques");
                });

            modelBuilder.Entity("Lesson_5.Models.Call", b =>
                {
                    b.HasOne("Lesson_5.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lesson_5.Models.Consultant", "Consultant")
                        .WithMany("Calls")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Consultant");
                });

            modelBuilder.Entity("Lesson_5.Models.Purchase", b =>
                {
                    b.HasOne("Lesson_5.Models.Consultant", "Consultant")
                        .WithMany()
                        .HasForeignKey("ConsultantId");

                    b.HasOne("Lesson_5.Models.Customer", "Customer")
                        .WithMany("Basket")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lesson_5.Models.Manager", null)
                        .WithMany("Purchases")
                        .HasForeignKey("ManagerId");

                    b.HasOne("Lesson_5.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lesson_5.Models.Supply", b =>
                {
                    b.HasOne("Lesson_5.Models.Manager", "Manager")
                        .WithMany("Supplies")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lesson_5.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lesson_5.Models.Provider", "Provider")
                        .WithMany("NewProducts")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Product");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Lesson_5.Models.Customer", b =>
                {
                    b.Navigation("Basket");
                });

            modelBuilder.Entity("Lesson_5.Models.Provider", b =>
                {
                    b.Navigation("NewProducts");
                });

            modelBuilder.Entity("Lesson_5.Models.Consultant", b =>
                {
                    b.Navigation("Calls");
                });

            modelBuilder.Entity("Lesson_5.Models.Manager", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("Supplies");
                });
#pragma warning restore 612, 618
        }
    }
}
